<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ImagingPipeline.PipelineCatalog</AssemblyName>
    <RootNamespace>ImagingPipeline.PipelineCatalog</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Update="configuration\pipelinecatalog.json" TargetPath="pipelinecatalog.json"
          CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <ProjectReference Include="..\pipeline-contracts\ImagingPipeline.PipelineContracts.csproj" />
    <ProjectReference Include="..\rabbitmq-configuration\ImagingPipeline.RabbitMqConfiguration.csproj" />
  </ItemGroup>
</Project>
