<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ImagingPipeline.UnifiedGateway</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\libs\pipeline-catalog\ImagingPipeline.PipelineCatalog.csproj" />
    <ProjectReference Include="..\..\libs\pipeline-contracts\ImagingPipeline.PipelineContracts.csproj" />
    <ProjectReference Include="..\..\libs\observability\ImagingPipeline.Observability.csproj" />
    <ProjectReference Include="..\..\libs\rule-engine\ImagingPipeline.RuleEngine.csproj" />
    <ProjectReference Include="..\..\libs\elasticsearch-client\ElasticsearchClient.csproj" />
    <ProjectReference Include="..\..\libs\rabbitmq-client\RabbitMqClient.csproj" />
  </ItemGroup>
</Project>
