<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ImagingPipeline.ElasticsearchClient</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elasticsearch.Net" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="NEST" />
  </ItemGroup>
</Project>
